# Generated by Django 3.0.6 on 2020-05-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
        ('clientes', '0002_cliente_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFactura', models.DateTimeField(auto_now=True)),
                ('subtotalFactura', models.FloatField()),
                ('ivaFactura', models.FloatField()),
                ('totalFactura', models.FloatField()),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('idTienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendas.Tienda')),
            ],
        ),
    ]
