# Generated by Django 3.0.6 on 2020-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=200)),
                ('telefonoCliente', models.CharField(max_length=8)),
                ('direccionCliente', models.CharField(max_length=200)),
                ('nitCliente', models.CharField(max_length=15)),
            ],
        ),
    ]
