# Generated by Django 3.0.4 on 2020-05-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_idcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='idCompras',
        ),
    ]
