# Generated by Django 3.0.4 on 2020-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='venceOferta',
            field=models.DateField(),
        ),
    ]
