# Generated by Django 3.0.4 on 2020-05-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_remove_pedido_idcompras'),
        ('productos', '0002_producto_descuentoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadRegistro', models.IntegerField()),
                ('precioUnidadRegistro', models.FloatField()),
                ('subtotalRegistro', models.FloatField()),
                ('descuentoRegistro', models.FloatField()),
                ('totalRegistro', models.FloatField()),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido')),
                ('idProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
    ]
