# Generated by Django 3.0.4 on 2020-06-02 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('pedidos', '0004_auto_20200519_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idEmpleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado'),
        ),
    ]
