# Generated by Django 3.0.6 on 2020-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTienda', models.CharField(max_length=40)),
                ('ubicacionTienda', models.CharField(max_length=100)),
                ('telefonoTienda', models.CharField(max_length=10)),
                ('faxTienda', models.CharField(max_length=30)),
            ],
        ),
    ]
