# Generated by Django 3.0.6 on 2020-05-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadCompra', models.IntegerField()),
                ('fechaCompra', models.DateTimeField(auto_now=True)),
                ('estadoCompra', models.CharField(max_length=30)),
                ('subtotalCompra', models.FloatField()),
                ('idProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
    ]
