# Generated by Django 3.0.4 on 2020-05-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
